Feature/buttons
FrontKid/Sladoled pull request #1
Opened 2022-12-22 08:46 UTC by NadiiaSharafutdinova

Added html for Products, images of products, mixins for buttons and links

2022-12-22 10:23 UTC, serhii-mask requested changes
Також не впевнений на рахунок зображень, бо напевно потрібно зразу робити окрему папку з всіма версіями фото

2022-12-22 10:23 UTC, serhii-mask commented on src/index.html
> -</body>
Бачу що видалила закриваючий тег боді, але не бачу чи добавила його

2022-12-22 10:23 UTC, serhii-mask commented on src/sass/main.css
> +body {
Це не має бути окремим сас файлом, де будуть загальні стилі?

2022-12-22 11:03 UTC, FrontKid commented on src/sass/main.css
> +body {
Так это и есть  отделные сас файл, это все в  _common.scss
А то что ты кинул это уже скомпилированный css

2022-12-22 11:29 UTC, FrontKid requested changes

2022-12-22 11:29 UTC, FrontKid commented on src/sass/main.scss
> +@import "./UI/buttons";
Это отдельный импорт должен быть по аналогии с тем что уже есть
/********************************************/
/*************** UI START *****************/ и тд

2022-12-22 11:29 UTC, FrontKid commented on src/sass/UI/_buttons.scss
> +height: 42px;
Эти стили указаны в боди их не нужно дублировать на кнопки и другие блоки если они без изменений, так как они будут наследовать эти свойства у родителя 
font-family: $font-family-mont;
font-size: 14px;

Высоту строк указываем в пикселях 
line-height: 1.29;

2022-12-22 11:29 UTC, FrontKid commented on src/sass/UI/_buttons.scss
> +    height: 38px;
У кнопок не должно быть фиксированной высоты и ширины
только падинги  со всех сторон, тогда не придется создавать отдельную кнопку для моб версии

2022-12-22 11:29 UTC, FrontKid commented on src/index.html
>  <body>
Боди не закрыт нигде

2022-12-22 11:29 UTC, FrontKid commented on src/index.html
> +<section class="products">
Этой секции не нужно создавать отдельный контейнер див, это лишний нод узел должно быть

section.product.container

2022-12-22 11:29 UTC, FrontKid commented on src/index.html
> +     <button class="product__link"></button>
Стрелка должна быть SVG элементом а не тегом button

2022-12-22 20:39 UTC, FrontKid requested changes

2022-12-22 20:39 UTC, FrontKid commented on src/index.html
> +      <div class="flex-container">
flex-cotainer был просто примером, нужно следовать бем методолгоии,  если это блок products то флекс контейнер может быть products__inner например

2022-12-22 20:39 UTC, FrontKid commented on src/sass/2-components/_products-section.scss
> +@media screen and (min-width: 480px) {
Все медиа внизу файла

2022-12-22 20:39 UTC, FrontKid commented on src/sass/main.scss
> +@import "./3-UI/buttons";
/************************************************/
/*========   UI START  =============/
/************************************************/
Вот сюда импорт с UI

/************************************************/
/*========   UI END ==============/
/************************************************/

2022-12-22 20:43 UTC, NadiiaSharafutdinova commented on src/sass/2-components/_products-section.scss
> +@media screen and (min-width: 480px) {
Є.

2022-12-22 20:52 UTC, NadiiaSharafutdinova commented on src/index.html
> +      <div class="flex-container">
Зробила, запушила

2022-12-22 20:55 UTC, NadiiaSharafutdinova commented on src/sass/main.scss
> +@import "./3-UI/buttons";
Готово. Підкажеш, коли можна видаляти бранч? (скоріш за все не дійду до компа завтра до 14)

2022-12-23 15:19 UTC, FrontKid requested changes

2022-12-23 15:19 UTC, FrontKid commented on src/sass/main.scss
> +/*======== UI START =============/
Исправь на комменты как у меня в этом же файле

2022-12-23 15:19 UTC, FrontKid commented on src/index.html
> +    <section class="products container">
Секция должна быть модулем в папке partials

2022-12-23 15:19 UTC, FrontKid commented on src/index.html
> +          <img class="product__image" src="../../Sladoled/assets/Products/product-icecream.png" alt="">
Неверно указан путь к картинке  и у тебя там дублируются картинки одни лежат в папке products вторые в assets

2022-12-23 15:20 UTC, FrontKid commented on src/sass/main.scss
> +@import "./3-UI/buttons";
Он сам удалится когда я добавлю ветку в мейн

2022-12-23 15:23 UTC, closed without merging

2022-12-23 15:24 UTC, FrontKid commented
Deleted branch