Feature/footer
FrontKid/Sladoled pull request #2
Opened 2022-12-22 08:52 UTC by MajaTrof

change container

2022-12-22 11:45 UTC, FrontKid requested changes

2022-12-22 11:45 UTC, FrontKid commented on src/sass/1-helpers/_common.scss
> +  max-width: 1200px;
Верни контейнер

2022-12-22 11:45 UTC, FrontKid commented on src/sass/1-helpers/_common.scss
> +    width: 768px;
ширина тут не нужна, тем более фиксированная

2022-12-22 13:12 UTC, MajaTrof commented on src/sass/1-helpers/_common.scss
> +  max-width: 1200px;
вернула

2022-12-22 13:12 UTC, MajaTrof commented on src/sass/1-helpers/_common.scss
> +    width: 768px;
ок

2022-12-22 20:28 UTC, FrontKid requested changes

2022-12-22 20:28 UTC, FrontKid commented on src/index.html
> +    <div class="wrapper"></div>
footer должен быть во wrapper

2022-12-22 20:28 UTC, FrontKid commented on package.json
> +    "update-browserslist-db": "^1.0.10"
Что это за пакет?

2022-12-22 20:28 UTC, FrontKid commented on src/index.html
> +          <ul>
Не должно быть тегов без класса, классы по БЕМ методологии именуем

2022-12-22 20:28 UTC, FrontKid commented on src/sass/2-components/_footer.scss
> +    width: 320px;
Не должно бытв фиксированой ширины, особенно в родителских блоках

2022-12-22 20:28 UTC, FrontKid commented on src/sass/2-components/_footer.scss
> +    @media screen and (min-width: $tablet-fixed) {
Медиа в самом низу файла должны быть

2022-12-22 20:28 UTC, FrontKid commented on src/sass/2-components/_footer.scss
> +// .footercard {
Комменты убираем все перед пушем, такого не должно быть в мейне

2022-12-22 20:28 UTC, FrontKid commented on src/sass/2-components/_footer.scss
> +.footercard__item {
Пробелов лищних не должно быть

2022-12-22 20:28 UTC, FrontKid commented on src/sass/main.scss
> +@import "./1-helpers/breakpoints";
Переменные должны быть в фалу _variables

2022-12-22 20:28 UTC, FrontKid commented on src/sass/main.scss
> +@import "./2-components/footer";
Перемести на 14 строку, между СТАРТ И ЭНД

2022-12-23 13:44 UTC, FrontKid requested changes

2022-12-23 13:44 UTC, FrontKid commented on src/sass/1-helpers/_placeholders.scss
> +%text {
Общие стили для параграфа, ссылок и пунктов меню в фале _common

2022-12-23 13:44 UTC, FrontKid commented on src/sass/main.scss
> +@import "./1-helpers/placeholders";
Напиши стили для тегов

2022-12-24 07:33 UTC, FrontKid requested changes

2022-12-24 07:33 UTC, FrontKid commented on partials/footer.html
> +<!DOCTYPE html>
Это лишнаяя строка тут

2022-12-24 22:39 UTC, FrontKid requested changes

2022-12-24 22:39 UTC, FrontKid commented on partials/footer.html
> +    <div class="footer-information">
У тебя несоответсвие блока с информацией на моб устройствах с макетом в тг скрин кинул

2022-12-25 08:34 UTC, illia-dobro commented on partials/footer.html
> +    <div class="footer-information">
По завданню тут дві секції: contacts і footer

2022-12-25 08:37 UTC, illia-dobro commented on partials/footer.html
> +        <p class="footer-social__contact">
По макету зліва від номеру телефону

2022-12-25 08:42 UTC, illia-dobro commented on partials/footer.html
> +          Feel free to contact </p>
По макету зліва від номеру телефону

2022-12-25 13:54 UTC, MajaTrof commented on partials/footer.html
> +<!DOCTYPE html>
у мене без цієї стрічки вибиває помилку, як це виправити?

2022-12-25 14:41 UTC, FrontKid commented on partials/footer.html
> +<!DOCTYPE html>
Какую ошибку

2022-12-25 14:43 UTC, MajaTrof commented on partials/footer.html
> +<!DOCTYPE html>
[{
	"message": "Doctype must be declared first.",
}]

2022-12-26 08:31 UTC, FrontKid requested changes

2022-12-26 08:31 UTC, FrontKid commented on partials/footer.html
> +        <button type="submit" class="footer-button__submit footer-button__submit--but1">
В  ul может быть только li элементы

2022-12-26 09:12 UTC, merged