Feature/products
FrontKid/Sladoled pull request #6
Opened 2022-12-23 15:00 UTC by NadiiaSharafutdinova

Included html as partial

2022-12-23 18:56 UTC, FrontKid requested changes

2022-12-23 18:56 UTC, FrontKid commented on partials/products.html
> +<section class="products container">
Седелал ревью в лс телеги

2022-12-24 07:41 UTC, FrontKid requested changes

2022-12-24 07:41 UTC, FrontKid commented on src/sass/1-helpers/_common.scss
> +p {
Этот тег тут лишний, он уже есть ниже

2022-12-24 07:41 UTC, FrontKid commented on src/index.html
> + <include src = "../partials/products.html">
`<include src = "../partials/products.html"><include/>` тег должен закрыватся

2022-12-24 10:07 UTC, NadiiaSharafutdinova commented on src/index.html
> + <include src = "../partials/products.html">
+

2022-12-24 10:07 UTC, NadiiaSharafutdinova commented on src/sass/1-helpers/_common.scss
> +p {
+

2022-12-24 22:12 UTC, FrontKid approved these changes

2022-12-24 22:14 UTC, merged