Feature/advantages
FrontKid/Sladoled pull request #8
Opened 2022-12-23 18:02 UTC by illia-dobro

2022-12-23 19:18 UTC, FrontKid requested changes

2022-12-23 19:18 UTC, FrontKid commented on src/index.html
> +    <include src="../partials/advantages.html"></include>
Блок advantages идет снизу about

2022-12-24 22:03 UTC, FrontKid requested changes

2022-12-24 22:03 UTC, FrontKid commented on partials/advantages.html
> +        <p class="advantages-list__text">
При 700 пикселях когда текст по центру, сделай ему max-width в 300 пикселей

2022-12-24 22:03 UTC, FrontKid commented on partials/advantages.html
> +  </div>
Где закрывается тег section

2022-12-25 07:58 UTC, illia-dobro commented on partials/advantages.html
> +  </div>
Додав

2022-12-25 07:58 UTC, illia-dobro commented on partials/advantages.html
> +        <p class="advantages-list__text">
Є

2022-12-25 11:16 UTC, FrontKid requested changes

2022-12-25 11:16 UTC, FrontKid commented on src/sass/2-components/_advantages.scss
> +    margin: 0 auto;
Отписал в тг

2022-12-26 09:55 UTC, merged